# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - sbb-container-gmdcltqndgmd

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://gmdcltqndgmd.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_1ad989990e29429bb8922575a02a425c }}
        password: ${{ secrets.AzureAppService_ContainerPassword_2848a8945a6b4459b2228814f5ba2973 }}
        
    - run : chmod 777 ./gradlew
      name : gradle file permission change
    
    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: gmdcltqndgmd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1ad989990e29429bb8922575a02a425c }}/sbb:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sbb-container-gmdcltqndgmd'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_6a606848d43242a99b377b9f4c742062 }}
        images: 'gmdcltqndgmd.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_1ad989990e29429bb8922575a02a425c }}/sbb:${{ github.sha }}'
